# -*- coding: utf-8 -*-
"""breast cancer detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WaCsFxVWB_9PESA_FyKv1zXSHCzzTPON

# importing libraries
"""

import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

dataset=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data.csv')

"""# importing dataset"""

dataset.head()

"""# finding missing values"""

dataset.isna().sum()

dt=dataset

dt.info()

"""# CLEANING THE DATA"""

dt.drop(dt.columns[[-1,0]],axis=1,inplace=True)

dt

dt['diagnosis'].value_counts()

"""FEATURE SCALING"""

from sklearn.model_selection import train_test_split
diag_map={'M':1,'B':0}
dt['diagnosis']=dt['diagnosis'].map(diag_map)

dt

x=dt[['radius_mean','texture_mean','perimeter_mean','concavity_mean','concave points_mean']]

y=dt[['diagnosis']]

x

y

x_test,x_train,y_test,y_train = train_test_split(x,y,test_size=0.2,random_state=0)

"""# LOGESTIC REGRESSION"""

from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

"""# MODEL-naive_bayes"""

from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)
GaussianNB()

gnb_y_pred=gnb.predict(x_test)
accuracy_score(gnb_y_pred,y_test)

"""# MODEL=KNN"""

from sklearn.neighbors import KNeighborsClassifier
Knn=KNeighborsClassifier()
Knn.fit(x_train,y_train)
Knn_y_pred=Knn.predict(x_test)

accuracy_score(Knn_y_pred,y_test)